import styles from "./EventPage.module.css";
import Image from "next/image";
import Head from "next/head";
import Header from "../../components/Header";
import Link from "next/link";
import Footer from "../../components/Footer";

export default function EventPage() {
  return (
    <div id="eventpage">
      <Head>
        <title>HMI | Event Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hm.png" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        />
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
        ></link>
      </Head>
      <Header />
      <div className={styles.eventpage}>
        <div className={styles["eventpage__container"]}>
          <div className={styles["left__section"]}>
            <div className={styles["eventpage__image"]}>
              <Image
                src="/bangkitlah.png"
                width="700"
                height="200"
                alt="logo bangkitlah"
              />
            </div>
            <div className={styles["eventpage__description"]}>
              <div className={styles["eventpage__description-title"]}>
                <h2>Deskripsi</h2>
              </div>
              <div className={styles["eventpage__description-caption"]}>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto
                  dicta debitis natus quae! Ut nulla voluptate aspernatur qui
                  quas expedita asperiores vitae nisi. Vel necessitatibus,
                  corporis ipsum expedita accusantium alias assumenda architecto
                  fugit culpa ratione sed sit dolores laborum vitae.
                </p>
                <h3>Syarat dan Ketentuan</h3>
                <h5>1. Syarat dan Ketentuan</h5>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Molestias eaque, ut ab hic distinctio esse facere iure debitis
                  officiis molestiae explicabo atque maxime aspernatur
                  blanditiis, repellendus ipsam officia facilis laborum!
                </p>
                <h5>2. Syarat dan Ketentuan</h5>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Molestias eaque, ut ab hic distinctio esse facere iure debitis
                  officiis molestiae explicabo atque maxime aspernatur
                  blanditiis, repellendus ipsam officia facilis laborum!
                </p>
                <h5>3. Syarat dan Ketentuan</h5>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Molestias eaque, ut ab hic distinctio esse facere iure debitis
                  officiis molestiae explicabo atque maxime aspernatur
                  blanditiis, repellendus ipsam officia facilis laborum!
                </p>
                <h5>4. Syarat dan Ketentuan</h5>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Molestias eaque, ut ab hic distinctio esse facere iure debitis
                  officiis molestiae explicabo atque maxime aspernatur
                  blanditiis, repellendus ipsam officia facilis laborum!
                </p>
                <h5>5. Syarat dan Ketentuan</h5>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Molestias eaque, ut ab hic distinctio esse facere iure debitis
                  officiis molestiae explicabo atque maxime aspernatur
                  blanditiis, repellendus ipsam officia facilis laborum!
                </p>
              </div>
            </div>
          </div>
          <div className={styles["right__section"]}>
            <div className={styles["rightsection__atas"]}>
              <div className={styles["title__event"]}>
                <h3>Millenial Service : BANGKITLAH</h3>
              </div>
              <div className={styles["schedule__event"]}>
                <div className={styles["date__event"]}>
                  <i className="fa-solid fa-calendar-days"></i>
                  <p>Rabu, 16 November 2022</p>
                </div>
                <div className={styles["time__event"]}>
                  <i className="fa-solid fa-clock"></i>
                  <p>17:00 - Selesai</p>
                </div>
                <div className={styles["location__event"]}>
                  <i className="fa-solid fa-location-dot"></i>
                  <p>JKI Higher Than Ever, Semarang</p>
                </div>
              </div>

              <div className={styles["organizer__event"]}>
                <div className={styles["organizer__event-logo"]}>
                  <img src="/hm.png" alt="logo HMI" />
                  <div className={styles["organizer__event-caption"]}>
                    <p>Diselenggarakan oleh</p>
                    <h4>HistoryMaker Impact</h4>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles["registration__event"]}>
              <div className={styles["invitation__event"]}>
                <div className={styles["ticket__logo"]}>
                  <i className="fa-solid fa-ticket"></i>
                  <p>
                    Kamu belum terdaftar. Silakan daftar terlebih dahulu dengan
                    klik tombol REGISTER dibawah.
                  </p>
                </div>
                <div className={styles["htm__event"]}>
                  <h5>HTM :</h5>
                  <h5>FREE</h5>
                </div>
                <div className={styles["button__register"]}>
                  <Link href="#">
                    <a>REGISTER</a>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
