import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Header from "../components/Header";
import MyHome from "../components/Home";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Your Place to Grow | HMI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hm.png" />
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
        ></link>
      </Head>
      <Header />
      <MyHome />
      {/* <About /> */}
    </div>
  );
};

export default Home;
